name: Publish to npm

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Bump version
        run: pnpm version patch --no-git-tag-version

      - name: Build package
        run: pnpm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish --access public